# Generated by Django 4.2.3 on 2023-07-05 08:35

from django.db import migrations, models
import time


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('otp_time', models.TimeField(default=time.time)),
                ('expire_time', models.TimeField(default=time.time)),
            ],
        ),
    ]
