# Generated by Django 4.2.3 on 2023-07-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp_base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('otp', models.IntegerField(blank=True, null=True, unique=True)),
                ('expire_time', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='expire_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
    ]
