# Generated by Django 4.2.3 on 2023-07-05 18:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_expire_time_alter_user_otp_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expire_time',
            field=models.TimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_time',
            field=models.TimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
